# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUInew.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1802, 925)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # Camera section
        self.Camera = QtWidgets.QLabel(self.centralwidget)
        self.Camera.setGeometry(QtCore.QRect(3, 3, 800, 550))
        self.Camera.setFrameShape(QtWidgets.QFrame.Box)
        self.Camera.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Camera.setLineWidth(5)
        self.Camera.setText("")
        self.Camera.setObjectName("Camera")
        self.Camera_label = QtWidgets.QLabel(self.centralwidget)
        self.Camera_label.setGeometry(QtCore.QRect(880, 10, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setWeight(75)
        self.Camera_label.setFont(font)
        self.Camera_label.setObjectName("Camera_label")
        
        # Button Connection Section
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(880, 50, 171, 210))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.Connect_btn = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setWeight(75)
        self.Connect_btn.setFont(font)
        self.Connect_btn.setObjectName("Connect_btn")
        self.Disconnect_btn = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setWeight(75)
        self.Disconnect_btn.setFont(font)
        self.Disconnect_btn.setObjectName("Disconnect_btn")
        self.Start_btn = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setWeight(75)
        self.Start_btn.setFont(font)
        self.Start_btn.setObjectName("Start_btn")
        self.Stop_btn = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setWeight(75)
        self.Stop_btn.setFont(font)
        self.Stop_btn.setObjectName("Stop_btn")
        self.Clear_Graph_btn_ = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setWeight(75)
        self.Clear_Graph_btn_.setFont(font)
        self.Clear_Graph_btn_.setObjectName("Clear_Graph_btn_")

        # Path choose Section
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(880, 300, 151, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        # Manual Control Section
        groupBox = QtWidgets.QGroupBox(self.centralwidget)
        groupBox.setGeometry(QtCore.QRect(1100, 50, 581, 300))
        layout = QtWidgets.QGridLayout(groupBox)
        # Các nút điều khiển
        self.btnFL = QtWidgets.QPushButton("FL")
        self.btnFR = QtWidgets.QPushButton("FR")
        self.btnBL = QtWidgets.QPushButton("BL")
        self.btnBR = QtWidgets.QPushButton("BR")
        self.btnLeft = QtWidgets.QPushButton("LEFT")
        self.btnRight = QtWidgets.QPushButton("RIGHT")
        self.btnForward = QtWidgets.QPushButton("FORWARD")
        self.btnBackward = QtWidgets.QPushButton("BACKWARD")
        self.btnStop = QtWidgets.QPushButton("STOP")
        self.btnRotateL = QtWidgets.QPushButton("⟲")
        self.btnRotateR = QtWidgets.QPushButton("⟳")

        # Radio button cho chế độ
        self.modeManual = QtWidgets.QRadioButton("Manual")
        self.modeAuto = QtWidgets.QRadioButton("Auto")
        self.modeManual.setChecked(True)

        # Thêm vào layout (giống hình bạn gửi)
        layout.addWidget(self.btnFL, 0, 0)
        layout.addWidget(self.btnForward, 0, 1)
        layout.addWidget(self.btnFR, 0, 2)

        layout.addWidget(self.btnLeft, 1, 0)
        layout.addWidget(self.btnStop, 1, 1)
        layout.addWidget(self.btnRight, 1, 2)

        layout.addWidget(self.btnBL, 2, 0)
        layout.addWidget(self.btnBackward, 2, 1)
        layout.addWidget(self.btnBR, 2, 2)

        layout.addWidget(self.btnRotateL, 3, 0)
        layout.addWidget(self.btnRotateR, 3, 2)

        layout.addWidget(self.modeManual, 4, 0)
        layout.addWidget(self.modeAuto, 4, 1)

        groupBox.setLayout(layout)
        
        # Data show Section
        self.EKF_predict = QtWidgets.QLabel(self.centralwidget)
        self.EKF_predict.setGeometry(QtCore.QRect(1200, 410, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        self.EKF_predict.setFont(font)
        self.EKF_predict.setObjectName("EKF_predict")
        
        self.V_measure = QtWidgets.QLabel(self.centralwidget)
        self.V_measure.setGeometry(QtCore.QRect(870, 450, 120, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        self.V_measure.setFont(font)
        self.V_measure.setObjectName("V_measure")
        
        self.V_predict = QtWidgets.QLabel(self.centralwidget)
        self.V_predict.setGeometry(QtCore.QRect(870, 490, 120, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        self.V_predict.setFont(font)
        self.V_predict.setObjectName("V_predict")
        
        self.x_aruco = QtWidgets.QLabel(self.centralwidget)
        self.x_aruco.setGeometry(QtCore.QRect(1100, 450, 100, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        self.x_aruco.setFont(font)
        self.x_aruco.setObjectName("x_aruco")
        
        self.x_predict = QtWidgets.QLabel(self.centralwidget)
        self.x_predict.setGeometry(QtCore.QRect(1100, 490, 100, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        self.x_predict.setFont(font)
        self.x_predict.setObjectName("x_predict")
        
        self.y_aruco = QtWidgets.QLabel(self.centralwidget)
        self.y_aruco.setGeometry(QtCore.QRect(1300, 450, 100, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        self.y_aruco.setFont(font)
        self.y_aruco.setObjectName("y_aruco")
        
        self.y_predict = QtWidgets.QLabel(self.centralwidget)
        self.y_predict.setGeometry(QtCore.QRect(1300, 490, 100, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        self.y_predict.setFont(font)
        self.y_predict.setObjectName("y_predict")
        
        self.yaw_aruco = QtWidgets.QLabel(self.centralwidget)
        self.yaw_aruco.setGeometry(QtCore.QRect(1490, 450, 140, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        self.yaw_aruco.setFont(font)
        self.yaw_aruco.setObjectName("yaw_aruco")
        
        self.yaw_predict = QtWidgets.QLabel(self.centralwidget)
        self.yaw_predict.setGeometry(QtCore.QRect(1490, 490, 140, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        self.yaw_predict.setFont(font)
        self.yaw_predict.setObjectName("yaw_predict")
        
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setWeight(75)
        self.V_measure_txt = QtWidgets.QTextEdit(self.centralwidget)
        self.V_measure_txt.setGeometry(QtCore.QRect(1000, 450, 81, 31))
        self.V_measure_txt.setObjectName("V_measure_txt")
        self.V_predict_txt = QtWidgets.QTextEdit(self.centralwidget)
        self.V_predict_txt.setGeometry(QtCore.QRect(1000, 490, 81, 31))
        self.V_predict_txt.setObjectName("V_predict_txt")
        self.x_aruco_txt = QtWidgets.QTextEdit(self.centralwidget)
        self.x_aruco_txt.setGeometry(QtCore.QRect(1200, 450, 81, 31))
        self.x_aruco_txt.setObjectName("x_predict_txt")
        self.x_predict_txt = QtWidgets.QTextEdit(self.centralwidget)
        self.x_predict_txt.setGeometry(QtCore.QRect(1200, 490, 81, 31))
        self.x_predict_txt.setObjectName("x_predict_txt")
        self.y_aruco_txt = QtWidgets.QTextEdit(self.centralwidget)
        self.y_aruco_txt.setGeometry(QtCore.QRect(1400, 450, 81, 31))
        self.y_aruco_txt.setObjectName("y_aruco_txt")
        self.y_predict_txt = QtWidgets.QTextEdit(self.centralwidget)
        self.y_predict_txt.setGeometry(QtCore.QRect(1400, 490, 81, 31))
        self.y_predict_txt.setObjectName("y_predict_txt")
        self.yaw_aruco_txt = QtWidgets.QTextEdit(self.centralwidget)
        self.yaw_aruco_txt.setGeometry(QtCore.QRect(1635, 450, 81, 31))
        self.yaw_aruco_txt.setObjectName("yaw_aruco_txt")
        self.yaw_predict_txt = QtWidgets.QTextEdit(self.centralwidget)
        self.yaw_predict_txt.setGeometry(QtCore.QRect(1635, 490, 81, 31))
        self.yaw_predict_txt.setObjectName("yaw_predict_txt")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1802, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # Realtime plot Section
        # Kích thước và vị trí cố định
        self.plot_widget = FigureCanvas(plt.Figure(figsize=(4, 3)))  # Biểu đồ 1
        self.plot_widget_1 = FigureCanvas(plt.Figure(figsize=(4, 3)))  # Biểu đồ 2
        self.plot_widget_2 = FigureCanvas(plt.Figure(figsize=(4, 3)))  # Biểu đồ 3
        self.plot_widget_3 = FigureCanvas(plt.Figure(figsize=(4, 3)))  # Biểu đồ 4

        self.plot_widget.setParent(self.centralwidget)
        self.plot_widget_1.setParent(self.centralwidget)
        self.plot_widget_2.setParent(self.centralwidget)
        self.plot_widget_3.setParent(self.centralwidget)

        # Đặt vị trí và kích thước
        self.plot_widget.setGeometry(QtCore.QRect(0, 580, 440, 330))
        self.plot_widget_1.setGeometry(QtCore.QRect(450, 580, 440, 330))    
        self.plot_widget_2.setGeometry(QtCore.QRect(900, 580, 440, 330))
        self.plot_widget_3.setGeometry(QtCore.QRect(1350, 580, 440, 330))

        # Cấu hình trục
        self.ax1 = self.plot_widget.figure.add_subplot(111)
        self.ax1.set_xlabel("x (cm)", labelpad=15)  # labelpad tăng khoảng cách để không bị che
        self.ax1.set_ylabel("y (cm)")

        self.ax2 = self.plot_widget_1.figure.add_subplot(111)
        self.ax2.set_xlabel("Time (s)", labelpad=15)
        self.ax2.set_ylabel("error x (cm)")

        self.ax3 = self.plot_widget_2.figure.add_subplot(111)
        self.ax3.set_xlabel("Time (s)", labelpad=15)
        self.ax3.set_ylabel("error y (cm)")

        self.ax4 = self.plot_widget_3.figure.add_subplot(111)
        self.ax4.set_xlabel("Time (s)", labelpad=15)
        self.ax4.set_ylabel("error yaw (degree)")

        # Điều chỉnh layout để tránh bị cắt chữ
        self.plot_widget.figure.tight_layout()
        self.plot_widget_1.figure.tight_layout()
        self.plot_widget_2.figure.tight_layout()
        self.plot_widget_3.figure.tight_layout()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Camera_label.setText(_translate("MainWindow", "Camera Frame"))
        self.Connect_btn.setText(_translate("MainWindow", "Connect"))
        self.Disconnect_btn.setText(_translate("MainWindow", "Disconnect"))
        self.Start_btn.setText(_translate("MainWindow", "Start"))
        self.Stop_btn.setText(_translate("MainWindow", "Stop"))
               
        self.Clear_Graph_btn_.setText(_translate("MainWindow", "Clear Graph"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Choose Path"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Square"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Circle"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Line X"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Line Y"))
        
        self.EKF_predict.setText(_translate("MainWindow", "EKF_predict"))
        self.V_measure.setText(_translate("MainWindow", "V_measure"))
        self.V_predict.setText(_translate("MainWindow", "V_predict"))
        self.x_aruco.setText(_translate("MainWindow", "x_aruco"))
        self.x_predict.setText(_translate("MainWindow", "x_predict"))
        self.y_aruco.setText(_translate("MainWindow", "y_aruco"))
        self.y_predict.setText(_translate("MainWindow", "y_predict"))
        self.yaw_aruco.setText(_translate("MainWindow", "yaw_aruco"))
        self.yaw_predict.setText(_translate("MainWindow", "yaw_predict"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())